//! Clipboard history: AppKit posts no pasteboard notifications, so a main-run-loop timer compares
//! `changeCount` (a cheap integer read) and only reads contents when it moves. Text only, kept in
//! memory, never written to disk. Items marked concealed or transient (password managers, per
//! nspasteboard.org) are skipped.

use std::cell::{Cell, RefCell};
use std::collections::VecDeque;
use std::ptr::NonNull;
use std::time::{SystemTime, UNIX_EPOCH};

use block2::RcBlock;
use objc2::rc::Retained;
use objc2_app_kit::{NSPasteboard, NSPasteboardTypeString, NSWorkspace};
use objc2_foundation::NSTimer;

const POLL_SECONDS: f64 = 0.5;
const MAX_ITEMS: usize = 200;
const MAX_CHARS: usize = 100_000;
const SKIP_TYPES: [&str; 3] =
    ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"];

#[derive(Clone)]
pub struct Clip {
    pub text: String,
    pub app: String,
    pub app_path: String,
    pub at: f64,
}

thread_local! {
    static HISTORY: RefCell<VecDeque<Clip>> = const { RefCell::new(VecDeque::new()) };
    static LAST_CHANGE: Cell<isize> = const { Cell::new(-1) };
    static OWN_CHANGE: Cell<isize> = const { Cell::new(-1) };
    static TIMER: RefCell<Option<Retained<NSTimer>>> = const { RefCell::new(None) };
}

fn now() -> f64 {
    SystemTime::now().duration_since(UNIX_EPOCH).map(|d| d.as_secs_f64()).unwrap_or(0.0)
}

/// Start polling. Returns false if already running.
pub fn watch() -> bool {
    if TIMER.with(|t| t.borrow().is_some()) {
        return false;
    }
    LAST_CHANGE.with(|c| c.set(NSPasteboard::generalPasteboard().changeCount()));
    let block = RcBlock::new(|_t: NonNull<NSTimer>| poll());
    let timer = unsafe { NSTimer::scheduledTimerWithTimeInterval_repeats_block(POLL_SECONDS, true, &block) };
    // A copy overwritten before the next poll is lost, so keep the gap close to POLL_SECONDS.
    timer.setTolerance(0.1);
    TIMER.with(|t| *t.borrow_mut() = Some(timer));
    true
}

/// Moo's own copies (copy actions, re-copying a history item) are attributed to Moo.
pub fn note_own_change() {
    OWN_CHANGE.with(|c| c.set(NSPasteboard::generalPasteboard().changeCount()));
}

fn poll() {
    let pb = NSPasteboard::generalPasteboard();
    let change = pb.changeCount();
    if LAST_CHANGE.with(|c| c.replace(change)) == change {
        return;
    }
    let types = pb.types();
    let skip = types.as_ref().is_some_and(|ts| {
        (0..ts.count()).any(|i| {
            let t = ts.objectAtIndex(i).to_string();
            SKIP_TYPES.contains(&t.as_str())
        })
    });
    if skip {
        return;
    }
    let Some(s) = pb.stringForType(unsafe { NSPasteboardTypeString }) else { return };
    let mut text = s.to_string();
    if text.trim().is_empty() {
        return;
    }
    if text.len() > MAX_CHARS {
        let mut cut = MAX_CHARS;
        while !text.is_char_boundary(cut) {
            cut -= 1;
        }
        text.truncate(cut);
    }
    let (app, app_path) = if OWN_CHANGE.with(|c| c.get()) == change {
        ("Moo".to_string(), String::new())
    } else {
        source_app()
    };
    HISTORY.with(|h| {
        let mut h = h.borrow_mut();
        h.retain(|c| c.text != text);
        h.push_front(Clip { text, app, app_path, at: now() });
        h.truncate(MAX_ITEMS);
    });
}

/// Moo never activates, so the frontmost app is where the copy happened.
fn source_app() -> (String, String) {
    let Some(a) = NSWorkspace::sharedWorkspace().frontmostApplication() else { return (String::new(), String::new()) };
    let name = a.localizedName().map(|n| n.to_string()).unwrap_or_default();
    let path = a.bundleURL().and_then(|u| u.path()).map(|p| p.to_string()).unwrap_or_default();
    (name, path)
}

/// Newest first; a non-empty query filters with the shared fuzzy matcher on the first line.
pub fn history(query: &str, limit: usize) -> Vec<Clip> {
    HISTORY.with(|h| {
        let h = h.borrow();
        if query.trim().is_empty() {
            return h.iter().take(limit).cloned().collect();
        }
        let titles: Vec<String> = h.iter().map(|c| preview(&c.text, 300)).collect();
        crate::index::fuzzy(query, &titles, limit).into_iter().map(|(i, _)| h[i].clone()).collect()
    })
}

pub fn clear() {
    HISTORY.with(|h| h.borrow_mut().clear());
}

/// Single line: whitespace runs collapsed, cut to `max` chars.
pub fn preview(text: &str, max: usize) -> String {
    let one: String = text.split_whitespace().collect::<Vec<_>>().join(" ");
    if one.chars().count() <= max {
        return one;
    }
    let mut s: String = one.chars().take(max.saturating_sub(1)).collect();
    s.push('…');
    s
}

pub fn ago(at: f64) -> String {
    let s = (now() - at).max(0.0);
    match s {
        s if s < 60.0 => "just now".into(),
        s if s < 3600.0 => format!("{}m ago", (s / 60.0) as u64),
        s if s < 86_400.0 => format!("{}h ago", (s / 3600.0) as u64),
        s => format!("{}d ago", (s / 86_400.0) as u64),
    }
}